name: "Explain CI Failure"
description: "Summarize CI failures into a readable explanation"
inputs:
  github_token:
    description: "GITHUB_TOKEN"
    required: true
  comment_on_pr:
    description: "Post failure summary as a PR comment"
    required: false
    default: "false"
  json_output:
    description: "Export failures as JSON via the failures_json output"
    required: false
    default: "false"
  check_patterns:
    description: "Check if errors match known failure patterns tracked in GitHub Issues"
    required: false
    default: "false"
  pattern_label:
    description: "Label used to find pattern-tracking issues"
    required: false
    default: "ci-failure-pattern"
  runbook_url:
    description: "Base URL for runbook links (e.g., https://wiki.example.com/runbooks)"
    required: false
    default: ""
  custom_rules:
    description: "JSON array of custom rules: [{\"name\": \"MyLinter\", \"pattern\": \"my-lint-error\", \"hint\": \"Run my-lint --fix\"}]"
    required: false
    default: ""
  flaky_detection:
    description: "Check recent runs to detect likely flaky tests"
    required: false
    default: "false"
  flaky_lookback:
    description: "Number of recent workflow runs to check for flaky detection"
    required: false
    default: "10"
  suggest_reviewers:
    description: "Suggest reviewers based on recent commits to failing files"
    required: false
    default: "false"
  deploy_risk:
    description: "Show deploy-risk level based on failure type"
    required: false
    default: "false"
outputs:
  failures_json:
    description: "JSON array of failure details (when json_output is enabled)"
runs:
  using: "node20"
  main: "dist/index.js"
